### PR TITLE
Allow all methods on /anything

### PR DESCRIPTION
**Pull request by macheins**
`/anything` already returns the used method, but only allows for `GET` requests.
With this extension `/anything` acts as an "echoserver" and additionally returns any sent data.

### CODE REVIEW

**Comment by macheins** [comment]
Also fixes #361

**Comment by MarekR22** [comment]
based on description it would be nice to rename to "/anything" to "/echo".

**Comment by kennethreitz** [comment]
thanks!

**Comment by dair-targ** [comment]
While filing #522 I was surprised that according to the standard much more HTTP methods exist beyond ones mentioned in this merge request. Is there a strong preference, or I'll just submit a patch to allow an arbitrary methods at `/anything`?

**Comment by jimmywarting** [comment]
Came here looking/suggesting for any method on "/anything" also

would like to be able to do any custom http method

**Pull request merged**
