### PR TITLE
Allow any HTTP method in /delay endpoint

### PR DESCRIPTION
**Pull request by tmenier**
Issue #224

### CODE REVIEW

**Comment by sigmavirus24** [comment]
LGTM. @kevin1024 @johnsheehan thoughts?

**Comment by johnsheehan** [comment]
what about `HEAD` and `OPTIONS`?

i think we should create a base list of methods and expand this to apply to all the non-method specific endpoints (basically everything except `/get`, `/post`, etc)

**Comment by tmenier** [comment]
I'd defer to you guys for implementation (or someone who knows python better than me), but to do this en masse it might make sense to make "any method" the default and decorate only those you want to limit (/get, /post, etc).

**Comment by darrelmiller** [comment]
@tmenier  I suggest we drop the HEAD method because HEAD is [not allowed to return a body](https://tools.ietf.org/html/rfc7231#section-4.3.2).  Some HTTP client libraries get upset when a HEAD returns a body and end up returning a 504.

**Comment by sigmavirus24** [comment]
I concur regarding dropping HEAD as an accepted method. That said, I'm curious about 

> Some HTTP client libraries get upset when a HEAD returns a body and end up returning a 504.

Which libraries? I'm disappointed (not surprised) that libraries would modify the status code and misrepresent the response to the user.

**Comment by darrelmiller** [comment]
@sigmavirus24 It's not that they changed the status arbitrarily.  They are just failing and there is no standard way to say "this server isn't serving valid HTTP".  This URL http://conference.hypermediaapi.com tries to return a body with HEAD.  I just tried with four different HTTP request tools.  One returns 500, the other 504, and the two chrome extensions say "no response".

**Comment by tmenier** [comment]
Sorry for the delay (no pun intended). This sort of fell off my radar. HEAD removed as suggested.

**Comment by fflorent** [comment]
Any news? That would be very handy

Florent

**Comment by kennethreitz** [comment]
feel free to re-open with a rebase!

**Pull request closed without merging**
