### PR TITLE
Add support for basic auth without a password

### LINKED ISSUE #356: Basic auth with no password
Basic auth is sometimes used where the username is an API key, and the password is blank.

Is there a way to make httpbin act in this way? I can see `https://httpbin.org/basic-auth/user/passwd`, would it be possible to also have `https://httpbin.org/basic-auth/user` for cases when there is no password.

I would then expect both of the following to work:

```
curl -u user:passwd https://httpbin.org/basic-auth/user/passwd
curl -u user: https://httpbin.org/basic-auth/user
```

Thanks for this project, it's great. I dont use python day-to-day but i'm happy to submit a pull request for this if you think it's a good idea.

### PR DESCRIPTION
**Pull request by domharrington**
Finally got round to working on this. Fixes #356.

It's my first time writing python, so let me know if the style isn't up to scratch. Also added some tests for basic auth because i couldnt see them anywhere else, but if i missed them and i've duplicated it, let me know.

### CODE REVIEW

**Comment by kennethreitz** [comment]
this looks solid, but a bit silly. i'm torn, personally.

**Comment by sigmavirus24** [comment]
@kennethreitz I agree that this seems silly. That said, httpbin doesn't seem to have a strict philosophy. Is it there to test the most common variations of things that people will see, or is there to allow folks to test everything? If we can decide on that, I think we can have clearer answers for different additions to the project.

**Comment by kennethreitz** [comment]
i think i'll opt against another endpoint, but thank you for your kind contribution! it's a sane one and a good one. just, unneccessary. reducing code coverage is always a good thing.

**Comment by kennethreitz** [comment]
✨🍰✨

**Pull request closed without merging**
